development: &default
  adapter: postgresql
  host: localhost
  database: moviedb_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: moviedb_test

production:
  <<: *default
  database: moviedb_production
